"""Built-in library models, generated by code."""
from __future__ import annotations

import math

T = math.tan(math.radians(22.5))  # tan 22.5° = sqrt(2) - 1
C = (0.5, 0.5)


def _kite_base() -> dict:
    return {
        "id": "kite-base",
        "title": "Kite Base",
        "category": "bases",
        "description": "The simplest base: fold two edges to a diagonal to make a kite. "
                       "It is the starting point of the fish and bird bases.",
        "segments": [
            ((0, 0), (1, 1), "F"),
            ((0, 0), (1, T), "V"),
            ((0, 0), (T, 1), "V"),
        ],
    }


def _preliminary_segments(swap: bool = False) -> list:
    m, v = ("V", "M") if swap else ("M", "V")
    return [
        ((0, 0), (1, 1), v),
        ((1, 0), (0, 1), v),
        (C, (0.5, 1), m),
        (C, (0.5, 0), m),
        (C, (0, 0.5), m),
        (C, (1, 0.5), v),
    ]


def _preliminary_base() -> dict:
    return {
        "id": "preliminary-base",
        "title": "Preliminary Base",
        "category": "bases",
        "description": "Also called the square base. Diagonals are valleys and the book "
                       "folds are mountains; it collapses into a small layered square.",
        "segments": _preliminary_segments(),
    }


def _waterbomb_base() -> dict:
    return {
        "id": "waterbomb-base",
        "title": "Waterbomb Base",
        "category": "bases",
        "description": "The inverse of the preliminary base: book folds are valleys and the "
                       "diagonals are mountains. It collapses into a triangle.",
        "segments": _preliminary_segments(swap=True),
    }


def _fish_base() -> dict:
    k = 1 / (1 + T)
    p1 = (k, 1 - k)  # incentre of the lower-right triangle
    p2 = (1 - k, k)  # incentre of the upper-left triangle
    return {
        "id": "fish-base",
        "title": "Fish Base",
        "category": "bases",
        "description": "Two kite folds from opposite corners plus two rabbit ears. "
                       "All angles are multiples of 22.5°.",
        "segments": [
            ((0, 0), (1, 1), "F"),
            ((0, 0), p1, "V"),
            ((1, 1), p1, "V"),
            ((1, 0), p1, "V"),
            ((0, 0), p2, "V"),
            ((1, 1), p2, "V"),
            ((0, 1), p2, "V"),
            (p1, p2, "M"),
        ],
    }


def _pleat_8() -> dict:
    return {
        "id": "pleat-8",
        "title": "Accordion Pleat (8ths)",
        "category": "tessellations",
        "description": "Seven parallel creases alternating mountain and valley. The simplest "
                       "tessellation and the building block of every pleated design.",
        "segments": [((k / 8, 0), (k / 8, 1), "M" if k % 2 else "V") for k in range(1, 8)],
    }


def _miura_ori() -> dict:
    n = 4
    off = 0.06
    xs = [i / n for i in range(n + 1)]
    ys = [j / n for j in range(n + 1)]
    shift = [off if j % 2 else 0.0 for j in range(n + 1)]
    zig = {i: ("M" if i % 2 else "V") for i in range(1, n)}
    opp = {"M": "V", "V": "M"}

    def pt(i: int, j: int) -> tuple[float, float]:
        x = xs[i] if i in (0, n) else xs[i] + shift[j]
        return (x, ys[j])

    segs = []
    for i in range(1, n):  # zig-zag columns, constant assignment
        for j in range(n):
            segs.append((pt(i, j), pt(i, j + 1), zig[i]))
    for j in range(1, n):  # straight horizontal rows, alternating segments
        for k in range(n):
            if j % 2:  # vertex's right segment matches its zig-zag
                asg = zig[k] if k >= 1 else opp[zig[1]]
            else:  # vertex's left segment matches its zig-zag
                asg = zig[k + 1] if k + 1 < n else opp[zig[n - 1]]
            segs.append((pt(k, j), pt(k + 1, j), asg))
    return {
        "id": "miura-ori",
        "title": "Miura-ori (4×4)",
        "category": "tessellations",
        "description": "A rigid-foldable tessellation of parallelograms used in solar panels "
                       "and maps. Pulling two corners collapses the whole sheet at once.",
        "segments": segs,
    }


def _square_twist() -> dict:
    a, b = 0.25, 0.75
    q = {"bl": (a, a), "br": (b, a), "tr": (b, b), "tl": (a, b)}
    segs = [
        (q["bl"], q["br"], "M"),
        (q["br"], q["tr"], "M"),
        (q["tr"], q["tl"], "M"),
        (q["tl"], q["bl"], "M"),
        # rays along the paper diagonals
        (q["bl"], (0, 0), "M"),
        (q["br"], (1, 0), "M"),
        (q["tr"], (1, 1), "M"),
        (q["tl"], (0, 1), "M"),
        # pleat rays parallel to the neighbouring diagonal ray
        (q["br"], (0.5, 0), "V"),
        (q["bl"], (0, 0.5), "V"),
        (q["tl"], (0.5, 1), "V"),
        (q["tr"], (1, 0.5), "V"),
    ]
    return {
        "id": "square-twist",
        "title": "Square Twist",
        "category": "tessellations",
        "description": "A central square rotates as four pleats fold around it. "
                       "Twists are the basic tile of twist tessellations.",
        "segments": segs,
    }


def _sonobe_unit() -> dict:
    segs = [
        ((0, 0.5), (1, 0.5), "F"),
        # edges folded to the centre line, reversed where the corner folds wrap them
        ((0, 0.25), (0.25, 0.25), "M"),
        ((0.25, 0.25), (0.75, 0.25), "V"),
        ((0.75, 0.25), (1, 0.25), "M"),
        ((0, 0.75), (0.25, 0.75), "M"),
        ((0.25, 0.75), (0.75, 0.75), "V"),
        ((0.75, 0.75), (1, 0.75), "M"),
        # corner folds (through both layers)
        ((0.25, 0.25), (0, 0.5), "V"),
        ((0.25, 0.25), (0, 0), "V"),
        ((0.75, 0.75), (1, 0.5), "V"),
        ((0.75, 0.75), (1, 1), "V"),
        # tab folds (through both layers)
        ((0.75, 0.25), (1, 0.5), "V"),
        ((0.75, 0.25), (1, 0), "V"),
        ((0.25, 0.75), (0, 0.5), "V"),
        ((0.25, 0.75), (0, 1), "V"),
    ]
    return {
        "id": "sonobe-unit",
        "title": "Sonobe Unit",
        "category": "modular",
        "description": "The classic modular unit by Mitsunobu Sonobe. Each unit has two tabs "
                       "and two pockets; three make a triangle, six make a cube.",
        "segments": segs,
        "extra_steps": [
            {
                "title": "Assemble the units",
                "kind": "assembly",
                "text": "Fold three units the same way. Slide the tab of one unit into the "
                        "pocket of the next until all three lock into a triangular pyramid. "
                        "For a cube, make six units: each face of the cube is the square "
                        "centre of one unit, and every tab tucks into a neighbour's pocket.",
            }
        ],
    }


_BUILDERS = [
    _kite_base,
    _preliminary_base,
    _waterbomb_base,
    _fish_base,
    _pleat_8,
    _miura_ori,
    _square_twist,
    _sonobe_unit,
]


def library_models() -> list[dict]:
    """Raw model specs (segments, not yet built)."""
    return [b() for b in _BUILDERS]
